### ISSUE TITLE
I want to attach a realsense sensor to the world. Can someone please help? Thanks in advance.

### ISSUE THREAD

**Issue by minku1219** [IFRA-Cranfield/ros2_SimRealRobotControl#1]

**Comment by minku1219** [comment]
I have tried using the plugin provided by pal-robotics but it didn't worked for me. Also i have used the official plugin from intel realsense but it doesn't shows the published topic in ros2 topic list.

**Comment by 8LTB8smile8angel8** [comment]
hi,man. I meet a question as follow:
![87303dd2b20e0e96e1516590d5d023a](https://github.com/IFRA-Cranfield/ros2_SimRealRobotControl/assets/139226775/3b53ea45-3727-4310-9b70-b7d58b8546db)

**Comment by IFRA-Cranfield** [comment]
Hi @8LTB8smile8angel8, 
You are getting that error message because you haven't installed the IFRA_LinkAttacher repository, which is needed for the object pick and place in Gazebo.
Instructions to install it (included in the README.md file):
```sh
cd ~/dev_ws/src
git clone https://github.com/IFRA-Cranfield/IFRA_LinkAttacher.git
cd ~/dev_ws
colcon build
```

Regards,
Mikel (IFRA-Cranfield)
