### ISSUE TITLE
ros2 run encountered problems

### ISSUE THREAD

**Issue by hhz0328** [IFRA-Cranfield/ros2_SimRealRobotControl#8]
xxx@hhz:~/dev_ws$ ros2 run ros2srrc_execution sequence.py --ros-args -p PROGRAM_FILENAME:="ur3" -p ROBOT_MODEL:="ur3" -p EE_MODEL:="robotiq_2f85" -p GzBr_ENV:="gazebo"

 --- Cranfield University --- 
        (c) IFRA Group        

ros2srrc_execution --> SEQUENCE EXECUTION
Python script -> sequence.py

[INFO] [1705907216.091645655] [ros2srrc_program_param]: PROGRAM_FILENAME ROS2 Parameter received: ur3
[INFO] [1705907216.109238656] [ros2srrc_robot_param]: ROBOT_MODEL ROS2 Parameter received: ur3
[INFO] [1705907216.125560796] [ros2srrc_ee_param]: EE_MODEL ROS2 Parameter received: robotiq_2f85
[INFO] [1705907216.142580490] [ros2srrc_gzbr_param]: GzBr_ENV ROS2 Parameter received: gazebo

**Waiting for ros2srrc_data/Sequence ACTION SERVER to be available...**

What should I do to get to the next step?

**Comment by NilsHeidemann** [comment]
If you want to execute a program on a real robot you have to launch robot bringup and moveit2 in another command window first. Heres the command for an UR3 robot:

ros2 launch ros2srrc_ur3_bringup ur3_bringup.launch.py

**Comment by hhz0328** [comment]
thanks for your answer.
